version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4510-4559:4510-4559"  # SQS, S3, etc.
    environment:
      - SERVICES=sqs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
