version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs, sns
      - AWS_ACCESS_KEY_ID=test  # Set AWS Access Key
      - AWS_SECRET_ACCESS_KEY=test  # Set AWS Secret Key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      - compass_network

  compass_application:  # Your actual service name
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this is the correct path
    environment:
      - AWS_ACCESS_KEY_ID=test  # Set AWS Access Key
      - AWS_SECRET_ACCESS_KEY=test  # Set AWS Secret Key
    depends_on:
      - localstack
    networks:
      - compass_network  # Use the same network as LocalStack
networks:
  compass_network:
    driver: bridge