-- Drop existing tables
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS BILLING_CODE;
DROP TABLE IF EXISTS SELLER;


-- Create table for BillingCode
CREATE TABLE IF NOT EXISTS BILLING_CODE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(19, 2)
);

-- Create table for Payment (adding status field)
CREATE TABLE IF NOT EXISTS PAYMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(19, 2),
    BILLING_CODE_ID BIGINT,
    STATUS VARCHAR(20)
);

-- Create table for Seller
CREATE TABLE IF NOT EXISTS SELLER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

-- Insert data into BillingCode
INSERT INTO BILLING_CODE (AMOUNT) VALUES (100.00);
INSERT INTO BILLING_CODE (AMOUNT) VALUES (200.00);
INSERT INTO BILLING_CODE (AMOUNT) VALUES (300.00);
INSERT INTO BILLING_CODE (AMOUNT) VALUES (400.00);
INSERT INTO BILLING_CODE (AMOUNT) VALUES (500.00);

-- Insert data into Payment
--INSERT INTO PAYMENT (AMOUNT, BILLING_CODE_ID) VALUES (200.00, 1);
--INSERT INTO PAYMENT (AMOUNT, BILLING_CODE_ID) VALUES (200.75, 2);
--INSERT INTO PAYMENT (AMOUNT, BILLING_CODE_ID) VALUES (200.75, 2);

INSERT INTO SELLER (NAME) VALUES ('Joao');
INSERT INTO SELLER (NAME) VALUES ('Maria');
INSERT INTO SELLER (NAME) VALUES ('Jessica');
INSERT INTO SELLER (NAME) VALUES ('Janaina');
INSERT INTO SELLER (NAME) VALUES ('Amanda');
