-- Drop existing tables
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS BILLING_CODE;
DROP TABLE IF EXISTS SELLER;

-- Create table for BillingCode
CREATE TABLE IF NOT EXISTS BILLING_CODE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(19, 2)
);

CREATE TABLE IF NOT EXISTS PAYMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(19, 2),
    BILLING_CODE_ID BIGINT,
    STATUS VARCHAR(20),
    FOREIGN KEY (BILLING_CODE_ID) REFERENCES BILLING_CODE(ID)
);

-- Create table for Seller
CREATE TABLE IF NOT EXISTS SELLER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

-- Insert data into BillingCode
INSERT INTO BILLING_CODE (AMOUNT) VALUES (100.00);
INSERT INTO BILLING_CODE (AMOUNT) VALUES (200.00);
INSERT INTO BILLING_CODE (AMOUNT) VALUES (300.00);
INSERT INTO BILLING_CODE (AMOUNT) VALUES (400.00);
INSERT INTO BILLING_CODE (AMOUNT) VALUES (500.00);

-- Insert data into Payment
INSERT INTO PAYMENT (AMOUNT, BILLING_CODE_ID, STATUS) VALUES (100.00, 1, 'FULL');
INSERT INTO PAYMENT (AMOUNT, BILLING_CODE_ID, STATUS) VALUES (150.00, 2, 'PARTIAL');
INSERT INTO PAYMENT (AMOUNT, BILLING_CODE_ID, STATUS) VALUES (400.00, 3, 'OVERPAID');

-- Insert data into Seller
INSERT INTO SELLER (NAME) VALUES ('Joao');
INSERT INTO SELLER (NAME) VALUES ('Maria');
INSERT INTO SELLER (NAME) VALUES ('Jessica');
INSERT INTO SELLER (NAME) VALUES ('Janaina');
INSERT INTO SELLER (NAME) VALUES ('Amanda');
