-- Drop existing tables
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS BILLING_CODE;
DROP TABLE IF EXISTS SELLER;

-- Create table for BillingCode
CREATE TABLE IF NOT EXISTS BILLING_CODE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(19, 2)
);

-- Create table for Payment (adding status field)
CREATE TABLE IF NOT EXISTS PAYMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(19, 2),
    BILLING_CODE_ID BIGINT,
    STATUS VARCHAR(20),
    FOREIGN KEY (BILLING_CODE_ID) REFERENCES BILLING_CODE(ID)
);

-- Create table for Seller
CREATE TABLE IF NOT EXISTS SELLER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);
